stages:
  - build
  - tests
  - publish_images

variables:
  BIND_CONTAINER_VERSION: "0.2.0"

#-----------------------------------------
build_image:
  stage: build
  tags:
    - shell
  variables:
    BUILD_OPTS: "--force-rm --no-cache"
  script:
    - docker build ${BUILD_OPTS} -t article714/bindns-container:${BIND_CONTAINER_VERSION} --build-arg BIND_CONTAINER_VERSION=${BIND_CONTAINER_VERSION} .

#------------------------------------------
# QCheck (TODO)

#------------------------------------------
# Tests

test_image:
  stage: tests
  image:
    name: article714/bindns-container:${BIND_CONTAINER_VERSION}
  services:
    - name: article714/bindns-container:${BIND_CONTAINER_VERSION}
      alias: bindns-srv
  tags:
    - docker
  script:
    # wait for bindns to be fully fit
    - echo "TODO"
    - dig @bindns-srv www.google.com

