stages:
  - build
  - tests
  - publish_images

variables:
  BIND_CERTIFICARE_VERSION: "0.0.2"
  DOCKER_REGISTRY_HOST: "83l02d2f.gra5.container-registry.ovh.net"

#-----------------------------------------
build_image:
  stage: build
  tags:
    - shell
  variables:
    BUILD_OPTS: "--force-rm --no-cache"
  script:
    - docker build ${BUILD_OPTS} -t certificare/bindns:${BIND_CERTIFICARE_VERSION} -t ${DOCKER_REGISTRY_HOST}/certificare/bindns:${BIND_CERTIFICARE_VERSION} --build-arg BIND_CERTIFICARE_VERSION=${BIND_CERTIFICARE_VERSION} .

#------------------------------------------
# QCheck (TODO)

#------------------------------------------
# Tests

test_image:
  stage: tests
  image:
    name: certificare/bindns:${BIND_CERTIFICARE_VERSION}
  services:
    - name: certificare/bindns:${BIND_CERTIFICARE_VERSION}
      alias: bindns-srv
  tags:
    - docker
  script:
    # wait for bindns to be fully fit
    - echo "TODO"
    - dig @bindns-srv www.google.com

#------------------------------------------
# Publish
publish_image:
  stage: publish_images
  tags:
    - shell
  only:
    refs:
      - production
  script:
    - docker push ${DOCKER_REGISTRY_HOST}/certificare/bindns:${BIND_CERTIFICARE_VERSION}
