#!/bin/sh
exec 2>&1

# Directories and init
if [ -d /var/lib/named ]; then
    chown -R bind:bind /var/lib/named
else
    mkdir -p /var/lib/named
    chown -R bind:bind /var/lib/named
fi

exec /usr/sbin/named -f -u bind
